# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [ ]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

In [2]:
import timeit
import numpy as np

In [3]:
numarray = np.arange(1000)

In [4]:
%timeit
numarray = numarray*2

In [5]:
code_to_test1 = """
import numpy as np
numarray = np.arange(1000)
numarray = numarray*2
"""

elapsed_time1 = timeit.timeit(code_to_test1, number =100)/100
print(elapsed_time1)


2.9571000000032653e-05


In [6]:
code_to_test2 = """
lista1 = list(range(0,1000,1))
for item in lista1:
    lista1[item] = lista1[item]*2
"""

elapsed_time2 = timeit.timeit(code_to_test2, number =100)/100
print(elapsed_time2)

0.0002851830000008704


In [7]:
lista1 = list(range(0,1000,1))
%time for _ in range(1000): lista2 = [x * 2 for x in lista1]  
%time for _ in range(1000): arr2 = numarray * 2

Wall time: 88 ms
Wall time: 4.01 ms


### Exercício 2

In [8]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0

In [9]:
array2 = np.arange(10)
array2

array2[5:9] = 0

array2

array([0, 1, 2, 3, 4, 0, 0, 0, 0, 9])

### Exercício 3

In [10]:
# Crie um array de 3 dimensões e imprima a dimensão 1 

In [11]:
dimarray = np.arange(27).reshape(3,3,3)
print(dimarray)
dimarray[2]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [12]:
dimarray2 = np.ones((3,3))*np.arange(3)
print(dimarray2)
dimarray[0,0,0]

[[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]


0

### Exercício 4

In [13]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

twodim = np.arange(9).reshape(3,3)
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(twodim)

twodim[2]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([6, 7, 8])

In [14]:
twodim[:1,1:]

array([[1, 2]])

### Exercício 5

In [15]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
print(arr, '\n')
transposta = np.transpose(arr)
print('\n',transposta)

tranp = arr.T
print(tranp)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 


 [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


### Exercício 6

In [16]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])


for idx, val in enumerate(cond):
    if val == True:
        print(xarr[idx])
    elif val == False:
        print(yarr[idx])

1.1
2.2
1.3
1.4
2.5


In [22]:
for x, y, b in zip(xarr, yarr, cond):
    print(x,y,b)

1.1 2.1 True
1.2 2.2 False
1.3 2.3 True
1.4 2.4 True
1.5 2.5 False


In [23]:
resultado = [(x if b else y) for x, y, b in zip(xarr, yarr, cond)]
resultado

[1.1, 2.2, 1.3, 1.4, 2.5]

### Exercício 7

In [ ]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B
# from tempfile import TemporaryFile
# X = TemporaryFile() #Instanciando o array
import numpy as np
A = np.linspace(0,100,10)
np.save('X.npy', A)

B = np.load('X.npy')
B

### Exercício 8

In [24]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])
obj

lista = []
for item in obj:
    if item in lista:
        None
    elif item not in lista:
        lista.append(item)
        
lista

['c', 'a', 'd', 'b']

In [25]:
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])
obj

#método implantado de valores únicos da Série

valoresunicos = obj.unique()
valoresunicos

array(['c', 'a', 'd', 'b'], dtype=object)

### Exercício 9

In [ ]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

In [ ]:
data = resp.json()
data

In [ ]:
issues = pd.DataFrame(data, columns=['number','title','labels','state'])
issues

### Exercício 10

In [ ]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas

In [26]:
import os 
os.remove("database.db") if os.path.exists("database.db") else None

In [27]:
import sqlite3

conexao = sqlite3.connect('database.db')

cursor = conexao.cursor()

In [28]:
def create_table():
    cursor.execute('CREATE TABLE IF NOT EXISTS ssd(id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, produto TEXT, '\
                'capacidade REAL, valor REAL)')

In [29]:
def inserir_dados(produto, capacidade, valor):
    cursor.execute('INSERT INTO ssd (produto, capacidade, valor) VALUES(?,?,?)', (produto, capacidade, valor))
    conexao.commit()

In [30]:
produto = ['970 evo plus', '860 evo', 'seagate']
capacidade = [500,1000,250]
valor = [470,350,250]

In [31]:
create_table()

In [32]:
for i in range(len(produto)):
    inserir_dados(produto[i],capacidade[i],valor[i])

In [33]:
cursor.execute('select * from ssd')

dados = cursor.fetchall()

for registro in dados:
    print(registro)

(1, '970 evo plus', 500.0, 470.0)
(2, '860 evo', 1000.0, 350.0)
(3, 'seagate', 250.0, 250.0)


In [34]:
cursor.close()
conexao.close()

In [35]:
from pandas import DataFrame

df = DataFrame(dados)

In [36]:
df.head()

0             1       2      3
0  1  970 evo plus   500.0  470.0
1  2       860 evo  1000.0  350.0
2  3       seagate   250.0  250.0

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>